sudo: required

matrix:
  include:
    - language: python
      python:
        - '3.6.1'

      env:
        - CODECOV_TOKEN=219366db-cfde-4936-967d-25072639f80f

      cache: pip

      install:
        - pip install codecov

      before_install:
        - sed '/django-heroku==/d' requirements.txt > requirements-build.txt

      script:
        - pip install -r requirements-build.txt
        - cd src
        - python manage.py makemigrations
        - python manage.py migrate
        - coverage run --omit=*/site-packages/* manage.py test comex_stat/assets

      after_success:
        - codecov

    - language: node_js
      node_js:
        - '8'

      cache:
        yarn: true

      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd docs/website && yarn install && GIT_USER="${GH_NAME}" GIT_BRANCH=master yarn run publish-gh-pages
