sudo: required

matrix:
  include:
    - language: python
      python:
        - '3.6.1'

      env:
        - CC_TEST_REPORTER_ID=cba7e65a3e4c938f1968478baa08ca245a354ec2d0fa85d12a2a62d54ad72a49

      cache: pip

      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build

      script:
        - pip install -r requirements.txt
        - cd src
        - python manage.py makemigrations
        - python manage.py migrate
        - coverage run --omit=*/site-packages/* manage.py test
        - coverage xml

      after_script:
        - ../cc-test-reporter after-build --coverage-input-type coverage.py --debug --exit-code $TRAVIS_TEST_RESULT

    - language: node_js
      node_js:
        - '8'

      cache:
        yarn: true

      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd docs/website && yarn install && GIT_USER="${GH_NAME}" GIT_BRANCH=master yarn run publish-gh-pages
