deploy:
  provider: pages
  skip-cleanup: true
  github-token: 23e22680b18c082f541b4ea581232afc803e5cac  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
