version: '3.5'

services:

  postgres:
    image: postgres:latest
    container_name: db
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=comexstat
      - POSTGRES_USER=comexstat
      - POSTGRES_DB=comexstat
    ports:
      - 5000:5432

  web:
    build: .
    command: /bin/sh ./boot.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=comexstat
      - DB_USER=comexstat
      - DB_PASSWORD=comexstat
      - DB_HOST=postgres
    depends_on:
      - postgres
