version: '3.5'

services:

  db:
    image: postgres
    ports:
      - 5000:5432

  web:
    build: .
    command: /bin/sh ./boot.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
