# Generated by Django 2.0.3 on 2018-09-14 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetExportFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('port_code', models.CharField(max_length=100)),
                ('transportation', models.CharField(max_length=100)),
                ('registries', models.BigIntegerField()),
                ('net_kilogram', models.FloatField()),
                ('fob_value', models.FloatField()),
                ('origin_fed_unit', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetImportFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('port_code', models.CharField(max_length=100)),
                ('transportation', models.CharField(max_length=100)),
                ('registries', models.BigIntegerField()),
                ('net_kilogram', models.FloatField()),
                ('fob_value', models.FloatField()),
                ('destination_fed_unit', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=250)),
                ('unid', models.CharField(max_length=100)),
                ('ppe', models.CharField(max_length=100)),
                ('ppi', models.CharField(max_length=100)),
                ('fat_agreg', models.CharField(max_length=100)),
                ('isic4', models.CharField(max_length=100)),
                ('exp_subset', models.CharField(max_length=100)),
                ('ncm_por', models.CharField(max_length=100)),
                ('ncm_en', models.CharField(max_length=100)),
                ('ncm_es', models.CharField(max_length=100)),
                ('siit', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='assetimportfacts',
            name='ncm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.NCM'),
        ),
        migrations.AddField(
            model_name='assetexportfacts',
            name='ncm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.NCM'),
        ),
    ]
