# Generated by Django 2.1.2 on 2018-11-09 18:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetExportFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('registries', models.BigIntegerField()),
                ('net_kilogram', models.FloatField()),
                ('fob_value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetImportFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('registries', models.BigIntegerField()),
                ('net_kilogram', models.FloatField()),
                ('fob_value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CGCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1_code', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('level1_name_pt', models.CharField(max_length=250)),
                ('level1_name_en', models.CharField(max_length=250)),
                ('level1_name_es', models.CharField(max_length=250)),
                ('level2_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('level2_name_pt', models.CharField(max_length=250)),
                ('level2_name_en', models.CharField(max_length=250)),
                ('level2_name_es', models.CharField(max_length=250)),
                ('level3_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('level3_name_pt', models.CharField(max_length=250)),
                ('level3_name_en', models.CharField(max_length=250)),
                ('level3_name_es', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name_pt', models.CharField(max_length=100)),
                ('country_name_en', models.CharField(max_length=100)),
                ('country_name_es', models.CharField(max_length=100)),
                ('country_code_iso3', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CUCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('item_name_pt', models.CharField(max_length=250)),
                ('item_name_en', models.CharField(max_length=250)),
                ('item_name_es', models.CharField(max_length=250)),
                ('subitem_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('subitem_name_pt', models.CharField(max_length=250)),
                ('subitem_name_en', models.CharField(max_length=250)),
                ('subitem_name_es', models.CharField(max_length=250)),
                ('position_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('position_name_pt', models.CharField(max_length=250)),
                ('position_name_en', models.CharField(max_length=250)),
                ('position_name_es', models.CharField(max_length=250)),
                ('chapter_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('chapter_name_pt', models.CharField(max_length=250)),
                ('chapter_name_en', models.CharField(max_length=250)),
                ('chapter_name_es', models.CharField(max_length=250)),
                ('section_code', models.CharField(max_length=1, verbose_name='Section code from NCM')),
                ('section_name_pt', models.CharField(max_length=250)),
                ('section_name_en', models.CharField(max_length=250)),
                ('section_name_es', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FederativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_name', models.CharField(max_length=100)),
                ('uf_code', models.CharField(max_length=100)),
                ('uf_initials', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('ncm_name_pt', models.CharField(max_length=250)),
                ('ncm_name_en', models.CharField(max_length=250)),
                ('ncm_name_es', models.CharField(max_length=250)),
                ('statistic_unit_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('ppe_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='Pauta de Produtos Exportados')),
                ('ppi_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='Pauta de Produtos Importados')),
                ('aggregate_factor_code', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('isic4_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='International Standard Industrial\n                                               Classification (Revision 4)')),
                ('exportation_subset', models.CharField(max_length=4)),
                ('siit_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='Setores Industriais por\n                                              Intensidade Tecnológica code')),
                ('cgce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.CGCE', verbose_name='Classificação por Grandes\n                                             Categorias Econômicas')),
                ('cuci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.CUCI', verbose_name='Classificação Uniforme do\n                                             Comércio Internacional')),
            ],
        ),
        migrations.CreateModel(
            name='SH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_code', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('chapter_name_pt', models.TextField(blank=True)),
                ('chapter_name_en', models.TextField()),
                ('chapter_name_es', models.TextField()),
                ('position_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('position_name_pt', models.TextField()),
                ('position_name_en', models.TextField()),
                ('position_name_es', models.TextField()),
                ('subposition_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')])),
                ('subposition_name_pt', models.TextField()),
                ('subposition_name_en', models.TextField()),
                ('subposition_name_es', models.TextField()),
                ('section_code', models.CharField(max_length=6, verbose_name='Section code from NCM')),
                ('section_name_pt', models.TextField()),
                ('section_name_en', models.TextField()),
                ('section_name_es', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeBlocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloc_name_pt', models.CharField(max_length=100)),
                ('bloc_name_en', models.CharField(max_length=100)),
                ('bloc_name_es', models.CharField(max_length=100)),
                ('bloc_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_name', models.CharField(max_length=100)),
                ('transportation_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urf_name', models.CharField(max_length=100)),
                ('urf_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ncm',
            name='sh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SH', verbose_name='Sistema Harmónico'),
        ),
        migrations.AddField(
            model_name='country',
            name='trade_bloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.TradeBlocs'),
        ),
        migrations.AddField(
            model_name='assetimportfacts',
            name='destination_fed_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.FederativeUnit'),
        ),
        migrations.AddField(
            model_name='assetimportfacts',
            name='ncm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.NCM'),
        ),
        migrations.AddField(
            model_name='assetimportfacts',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Country'),
        ),
        migrations.AddField(
            model_name='assetimportfacts',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Transportation'),
        ),
        migrations.AddField(
            model_name='assetimportfacts',
            name='urf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Urf'),
        ),
        migrations.AddField(
            model_name='assetexportfacts',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Country'),
        ),
        migrations.AddField(
            model_name='assetexportfacts',
            name='ncm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.NCM'),
        ),
        migrations.AddField(
            model_name='assetexportfacts',
            name='origin_fed_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.FederativeUnit'),
        ),
        migrations.AddField(
            model_name='assetexportfacts',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Transportation'),
        ),
        migrations.AddField(
            model_name='assetexportfacts',
            name='urf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Urf'),
        ),
    ]
