# Generated by Django 2.0.3 on 2018-09-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name_pt', models.CharField(max_length=100)),
                ('country_name_en', models.CharField(max_length=100)),
                ('country_name_sp', models.CharField(max_length=100)),
                ('country_code_iso3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FedUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_name', models.CharField(max_length=100)),
                ('uf_code', models.CharField(max_length=100)),
                ('uf_initials', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TradeBlocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloc_name_pt', models.CharField(max_length=100)),
                ('bloc_name_en', models.CharField(max_length=100)),
                ('bloc_name_sp', models.CharField(max_length=100)),
                ('bloc_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_name', models.CharField(max_length=100)),
                ('transportation_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urf_name', models.CharField(max_length=100)),
                ('urf_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='assetexportfacts',
            name='port',
        ),
        migrations.RemoveField(
            model_name='assetexportfacts',
            name='port_code',
        ),
        migrations.RemoveField(
            model_name='assetimportfacts',
            name='port',
        ),
        migrations.RemoveField(
            model_name='assetimportfacts',
            name='port_code',
        ),
        migrations.AlterField(
            model_name='assetexportfacts',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Country'),
        ),
        migrations.AlterField(
            model_name='assetexportfacts',
            name='origin_fed_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.FedUnit'),
        ),
        migrations.AlterField(
            model_name='assetexportfacts',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Transportation'),
        ),
        migrations.AlterField(
            model_name='assetimportfacts',
            name='destination_fed_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.FedUnit'),
        ),
        migrations.AlterField(
            model_name='assetimportfacts',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Country'),
        ),
        migrations.AlterField(
            model_name='assetimportfacts',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Transportation'),
        ),
        migrations.AddField(
            model_name='country',
            name='trade_bloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.TradeBlocs'),
        ),
        migrations.AddField(
            model_name='assetexportfacts',
            name='urf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Urf'),
        ),
        migrations.AddField(
            model_name='assetimportfacts',
            name='urf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Urf'),
        ),
    ]
