# Generated by Django 2.0.3 on 2018-09-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuci_item', models.CharField(max_length=250)),
                ('cuci_item_por', models.CharField(max_length=250)),
                ('cuci_item_ing', models.CharField(max_length=250)),
                ('cuci_item_esp', models.CharField(max_length=250)),
                ('cuci_sub', models.CharField(max_length=250)),
                ('cuci_sub_por', models.CharField(max_length=250)),
                ('cuci_sub_ing', models.CharField(max_length=250)),
                ('cuci_sub_esp', models.CharField(max_length=250)),
                ('cuci_pos', models.CharField(max_length=250)),
                ('cuci_pos_por', models.CharField(max_length=250)),
                ('cuci_pos_ing', models.CharField(max_length=250)),
                ('cuci_pos_esp', models.CharField(max_length=250)),
                ('cuci_cap', models.CharField(max_length=250)),
                ('cuci_cap_por', models.CharField(max_length=250)),
                ('cuci_cap_ing', models.CharField(max_length=250)),
                ('cuci_cap_esp', models.CharField(max_length=250)),
                ('cuci_sec', models.CharField(max_length=250)),
                ('cuci_sec_por', models.CharField(max_length=250)),
                ('cuci_sec_ing', models.CharField(max_length=250)),
                ('cuci_sec_esp', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='ncm',
            name='cuci',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assets.CUCI'),
            preserve_default=False,
        ),
    ]
