# Generated by Django 2.1.2 on 2018-11-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuci',
            name='chapter_name_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='chapter_name_es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='chapter_name_pt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='item_name_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='item_name_es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='item_name_pt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='position_name_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='position_name_es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='position_name_pt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='section_name_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='section_name_es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='section_name_pt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='subitem_name_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='subitem_name_es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuci',
            name='subitem_name_pt',
            field=models.TextField(),
        ),
    ]
