# Generated by Django 2.0.3 on 2018-09-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgce_n1', models.CharField(max_length=250)),
                ('cgce_n1_pt', models.CharField(max_length=250)),
                ('cgce_n1_en', models.CharField(max_length=250)),
                ('cgce_n1_es', models.CharField(max_length=250)),
                ('cgce_n2', models.CharField(max_length=250)),
                ('cgce_n2_pt', models.CharField(max_length=250)),
                ('cgce_n2_en', models.CharField(max_length=250)),
                ('cgce_n2_es', models.CharField(max_length=250)),
                ('cgce_n3', models.CharField(max_length=250)),
                ('cgce_n3_pt', models.CharField(max_length=250)),
                ('cgce_n3_en', models.CharField(max_length=250)),
                ('cgce_n3_es', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh2', models.CharField(max_length=250)),
                ('sh2_pt', models.CharField(max_length=250)),
                ('sh2_en', models.CharField(max_length=250)),
                ('sh2_es', models.CharField(max_length=250)),
                ('sh4', models.CharField(max_length=250)),
                ('sh4_pt', models.CharField(max_length=250)),
                ('sh4_en', models.CharField(max_length=250)),
                ('sh4_es', models.CharField(max_length=250)),
                ('sh6', models.CharField(max_length=250)),
                ('sh6_pt', models.CharField(max_length=250)),
                ('sh6_en', models.CharField(max_length=250)),
                ('sh6_es', models.CharField(max_length=250)),
                ('ncm_secrom', models.CharField(max_length=250)),
                ('sec_pt', models.CharField(max_length=250)),
                ('sec_en', models.CharField(max_length=250)),
                ('sec_es', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_cap_por',
            new_name='cuci_cap_pt',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_item_por',
            new_name='cuci_item_pt',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_pos_por',
            new_name='cuci_pos_pt',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_sec_por',
            new_name='cuci_sec_pt',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_sub_por',
            new_name='cuci_sub_pt',
        ),
        migrations.RenameField(
            model_name='ncm',
            old_name='ncm_por',
            new_name='ncm_pt',
        ),
        migrations.AddField(
            model_name='ncm',
            name='cgce',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assets.CGCE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ncm',
            name='sh',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assets.SH'),
            preserve_default=False,
        ),
    ]
