# Generated by Django 2.1.2 on 2018-11-15 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181109_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='aggregate_factor_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')]),
        ),
    ]
