# Generated by Django 2.0.3 on 2018-09-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180919_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_cap_esp',
            new_name='cuci_cap_en',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_cap_ing',
            new_name='cuci_cap_es',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_item_esp',
            new_name='cuci_item_en',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_item_ing',
            new_name='cuci_item_es',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_pos_esp',
            new_name='cuci_pos_en',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_pos_ing',
            new_name='cuci_pos_es',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_sec_esp',
            new_name='cuci_sec_en',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_sec_ing',
            new_name='cuci_sec_es',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_sub_esp',
            new_name='cuci_sub_en',
        ),
        migrations.RenameField(
            model_name='cuci',
            old_name='cuci_sub_ing',
            new_name='cuci_sub_es',
        ),
    ]
