# Generated by Django 2.0.3 on 2018-09-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180920_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_name_sp',
            new_name='country_name_es',
        ),
        migrations.RenameField(
            model_name='tradeblocs',
            old_name='bloc_name_sp',
            new_name='bloc_name_es',
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code_iso3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='fedunit',
            name='uf_initials',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='tradeblocs',
            name='bloc_code',
            field=models.CharField(max_length=10),
        ),
    ]
