# Generated by Django 2.0.3 on 2018-09-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180921_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_code_iso3',
            new_name='code_iso3',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name_en',
            new_name='name_english',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name_pt',
            new_name='name_portuguese',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name_es',
            new_name='name_spanish',
        ),
        migrations.RenameField(
            model_name='tradeblocs',
            old_name='bloc_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='tradeblocs',
            old_name='bloc_name_en',
            new_name='name_english',
        ),
        migrations.RenameField(
            model_name='tradeblocs',
            old_name='bloc_name_pt',
            new_name='name_portuguese',
        ),
        migrations.RenameField(
            model_name='tradeblocs',
            old_name='bloc_name_es',
            new_name='name_spanish',
        ),
        migrations.RenameField(
            model_name='transportation',
            old_name='transportation_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='transportation',
            old_name='transportation_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='urf',
            old_name='urf_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='urf',
            old_name='urf_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='assetexportfacts',
            name='origin_fed_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.FederativeUnit'),
        ),
        migrations.AlterField(
            model_name='assetimportfacts',
            name='destination_fed_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.FederativeUnit'),
        ),
        migrations.DeleteModel(
            name='FedUnit',
        ),
    ]
