# Generated by Django 2.1.2 on 2018-11-15 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181115_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='isic4_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='International Standard Industrial\n                                               Classification (Revision 4)'),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='siit_code',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='Setores Industriais por\n                                              Intensidade Tecnológica code'),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='statistic_unit_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')]),
        ),
    ]
