# Generated by Django 2.1.2 on 2018-11-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181115_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='ncm_name_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='ncm_name_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='ncm_name_pt',
            field=models.TextField(null=True),
        ),
    ]
