# Generated by Django 2.1.2 on 2018-11-15 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20181115_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='aggregate_factor_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='exportation_subset',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='isic4_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='International Standard Industrial\n                                               Classification (Revision 4)'),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='ppe_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='Pauta de Produtos Exportados'),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='ppi_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')], verbose_name='Pauta de Produtos Importados'),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='statistic_unit_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos', regex='^[0-9]+$')]),
        ),
    ]
